name: Python Application

on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 7 * * *'  # 每天运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        GPT_VERSION: ${{ secrets.GPT_VERSION }}
        SCHEDULE_PROMPT: ${{ secrets.SCHEDULE_PROMPT }}
        USERNAME: ${{ secrets.USERNAME }}
        USER_CAREER: ${{ secrets.USER_CAREER }}
        PRESENT_LOCATION: ${{ secrets.PRESENT_LOCATION }}
      run: |
        python main.py  # 替换为你的主脚本路径

